baseURL = 'https://yazaki.lab.uec.ac.jp/'
languageCode = 'ja-jp'
title = '矢﨑研究室 Yazaki Lab.'
#theme = 'yazaki-lab'
theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]

[menus]
#[[menus.main]]
#    name = 'Top'
#    pageRef = '/'
#    weight = 10
# [[menus.main]]
#    name = '記事一覧'
#    pageRef = '/posts'
#    weight = 20
[[menus.main]]
    name = 'About'
    pageRef = '/about'
    weight = 30
[[menus.main]]
    name = 'Member'
    pageRef = '/members'
    weight = 40
[[menus.main]]
    name = 'Publish'
    pageRef = '/papers'
    weight = 50
[[menus.main]]
    name = 'Projects'
    pageRef = '/theses'
    weight = 60
#[[menus.main]]
#    name = 'Contact'
#    pageRef = '/contact'
#    weight = 70

[params]
subtitle = "The University of Electro-Communications"

[[params.links]]
name = "教員のX"
url = "https://twitter.com/syunjiyazaki"

[[params.links]]
name = "情報基盤センター"
url = "http://www.cc.uec.ac.jp/"

[[params.ananke_socials]]
name = "X"
url = "https://twitter.com/syunjiyazaki"
