baseURL = 'https://yazaki.lab.uec.ac.jp/'
languageCode = 'ja-jp'
title = '電気通信大学 矢﨑研究室'
#theme = 'yazaki-lab'
theme = ["github.com/theNewDynamic/gohugo-theme-ananke/v2"]

[menus]
    [[menus.main]]
        name = 'Members'
        url = '/members'
        weight = 40
    [[menus.main]]
        name = 'Publications'
        url = '/publications'
        weight = 50
    [[menus.main]]
        name = 'Projects'
        url = '/projects'
        weight = 60
    [[menus.main]]
        name = 'For UEC Students'
        url = 'https://sites.google.com/gl.cc.uec.ac.jp/yazaki-lab/'
        weight = 70

[params]
    subtitle = "The University of Electro-Communications"

    custom_css = ["custom.css"]
    body_classes = "custom"

    [[params.links]]
    name = "教員のX"
    url = "https://twitter.com/syunjiyazaki"

    [[params.links]]
    name = "情報基盤センター"
    url = "http://www.cc.uec.ac.jp/"

    [[params.ananke_socials]]
    name = "SNS (X)"
    url = "https://twitter.com/syunjiyazaki"
