local_backend: true

backend:
  name: git-gateway

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "post"
    label: "Post"
    description: "記事一覧へ表示される記事"
    folder: "content/posts"
    path: "{{slug}}"
    create: true
    # filter: {field: "slug", value: "_index"}
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DDTHH:mm:ss+09:00"}
      - {label: "Draft", name: "draft", widget: "boolean", hint: "trueにすると下書きになります"}
      - {label: "Body", name: "body", widget: "markdown"}
    view_groups:
      - label: Year
        field: date
        pattern: \d{4}
      - label: Drafts
        field: draft
  - name: "menu"
    label: "Menu"
    description: "固定ページ"
    files:
      - label: "Top Page"
        name: "index"
        file: "content/_index.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - label: "Members"
        name: "members"
        file: "content/members.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - label: "Publications"
        name: "publications"
        file: "content/publications.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}

